var setup = require("./setup.js");
var ast = setup();
var phoneParts = [];
ast.translate(phoneParts);
console.log();
console.log("test: translate AST");
console.log("phone number: ");
console.log("   area-code: " + phoneParts["area-code"]);
console.log("      office: " + phoneParts["office"]);
console.log("  subscriber: " + phoneParts["subscriber"]);
