// Generated by JavaScript APG, Version 2.0 [`apg-js2`](https://github.com/ldthomas/apg-js2)
module.exports = function(){
"use strict";
  //```
  // SUMMARY
  //      rules = 2
  //       udts = 0
  //    opcodes = 6
  //        ALT = 0
  //        CAT = 1
  //        RNM = 1
  //        UDT = 0
  //        BKR = 0
  //        REP = 1
  //        AND = 0
  //        NOT = 0
  //        BKA = 1
  //        BKN = 0
  //        TLS = 1
  //        TBS = 0
  //        TRG = 1
  // characters = [32 - 126]
  //```
  /* CALLBACK LIST PROTOTYPE (true, false or function reference) */
  this.callbacks = [];
  this.callbacks['rule'] = false;
  this.callbacks['text'] = false;

  /* OBJECT IDENTIFIER (for internal parser use) */
  this.grammarObject = 'grammarObject';

  /* RULES */
  this.rules = [];
  this.rules[0] = {name: 'rule', lower: 'rule', index: 0, isBkr: false};
  this.rules[1] = {name: 'text', lower: 'text', index: 1, isBkr: false};

  /* UDTS */
  this.udts = [];

  /* OPCODES */
  /* rule */
  this.rules[0].opcodes = [];
  this.rules[0].opcodes[0] = {type: 2, children: [1,3]};// CAT
  this.rules[0].opcodes[1] = {type: 3, min: 0, max: Infinity};// REP
  this.rules[0].opcodes[2] = {type: 4, index: 1};// RNM(text)
  this.rules[0].opcodes[3] = {type: 15};// BKA
  this.rules[0].opcodes[4] = {type: 7, string: [32,101,110,100]};// TLS

  /* text */
  this.rules[1].opcodes = [];
  this.rules[1].opcodes[0] = {type: 5, min: 32, max: 126};// TRG

  // The `toString()` function will display the original grammar file(s) that produced these opcodes.
  this.toString = function(){
    var str = "";
    str += "rule = *text &&\" end\"\n";
    str += "text = %d32-126\n";
    return str;
  }
}
